import { defineStore } from 'pinia'
import { ref, computed } from 'vue'
import { phoneLogin as phoneLoginApi, getMe } from '@/api/auth'
import {
  getToken, setToken, removeToken,
  getUserInfo, setUserInfo, removeUserInfo,
  getRefreshToken, setRefreshToken, removeRefreshToken,
  getRemember,
} from '@/utils/storage'
import type { UserVO } from '@/types/models'

/** Detect auto-generated names like "用户6889" */
function isAutoGeneratedName(name: string): boolean {
  return /^用户\d+$/.test(name)
}

function getMaskedPhone(user: UserVO): string {
  const phone = user.mobile || user.username || ''
  if (phone.length >= 11) {
    return phone.slice(0, 3) + '****' + phone.slice(7)
  }
  return phone
}

export const useUserStore = defineStore('user', () => {
  const remember = ref(getRemember())
  const token = ref<string>(getToken() || '')
  const refreshToken = ref<string>(getRefreshToken() || '')
  const userInfo = ref<UserVO | null>(getUserInfo() as UserVO | null)
  const initialized = ref(false)

  const isLoggedIn = computed(() => !!token.value)
  const userName = computed(() => userInfo.value?.realName || userInfo.value?.name || '')
  const userAvatar = computed(() => userInfo.value?.avatar || '')

  /** Display name: realName > non-auto-generated name > masked phone > "用户" */
  const displayName = computed(() => {
    const u = userInfo.value
    if (!u) return '用户'
    if (u.realName) return u.realName
    if (u.name && !isAutoGeneratedName(u.name)) return u.name
    const masked = getMaskedPhone(u)
    if (masked) return masked
    return '用户'
  })

  /** Display avatar initial */
  const displayInitial = computed(() => {
    const name = displayName.value
    if (name === '用户') return 'U'
    return name.charAt(0).toUpperCase()
  })

  /** 求职者角色 ID */
  const CANDIDATE_ROLE_ID = '300008'

  /** 当前用户是否是求职者 */
  const isCandidate = computed(() => {
    const roleIds = userInfo.value?.roleIds
    if (!roleIds) return false
    const ids = roleIds.split(',').map(id => id.trim()).filter(Boolean)
    return ids.length === 1 && ids[0] === CANDIDATE_ROLE_ID
  })

  async function phoneLogin(mobile: string, verificationCode: string, rememberMe = false) {
    const res = await phoneLoginApi({ mobile, verificationCode })
    token.value = res.accessToken
    refreshToken.value = res.refreshToken
    userInfo.value = res.userInfo
    remember.value = rememberMe
    initialized.value = true

    setToken(res.accessToken, rememberMe)
    setRefreshToken(res.refreshToken, rememberMe)
    setUserInfo(res.userInfo as unknown as Record<string, unknown>, rememberMe)
    return res
  }

  async function fetchUserInfo() {
    try {
      const user = await getMe()
      userInfo.value = user
      initialized.value = true
      setUserInfo(user as unknown as Record<string, unknown>, remember.value)
    } catch {
      logout()
    }
  }

  function logout() {
    token.value = ''
    refreshToken.value = ''
    userInfo.value = null
    initialized.value = false
    remember.value = false
    removeToken()
    removeRefreshToken()
    removeUserInfo()
  }

  return {
    token,
    refreshToken,
    userInfo,
    remember,
    initialized,
    isLoggedIn,
    isCandidate,
    userName,
    userAvatar,
    displayName,
    displayInitial,
    phoneLogin,
    fetchUserInfo,
    logout,
  }
})
